### ISSUE TITLE
Error when duplicates name

### ISSUE THREAD

**Issue by DavidCruciani** [MISP/PyMISPGalaxies#26]
Same name and result in pymispgalaxies upon removal of disarm-techniques:

https://github.com/MISP/misp-galaxy/blob/main/galaxies/mitre-ics-techniques.json
https://github.com/MISP/misp-galaxy/blob/main/galaxies/disarm-techniques.json

**Comment by Rafiot** [comment]
Fixed by: https://github.com/MISP/PyMISPGalaxies/commit/8df24c179d75132bf65d38bd40fa263e501732f8
