### ISSUE TITLE
meta is missing in dict 

### ISSUE THREAD

**Issue by sebdraven** [MISP/PyMISPGalaxies#6]
I try to catch meta in dict to add some context, and these field seems missing.

![image](https://user-images.githubusercontent.com/1478484/234316923-f8418676-4104-41ce-9bb3-9c31cac0901b.png)

**Comment by Rafiot** [comment]
Could it be because the packaged galaxies were from... last year? I just updated it and will release a package in a few min.

**Comment by Rafiot** [comment]
Ok, not just that, sorry.

The meta are there when I do that:

```
for a, b in c.get('malpedia').items():
    print(a, b.meta.to_json())

```

Not sure what I was on when I developed this library, it is... interestingly done to say the least. You shouldn't do `cluster_malpedia.cluster['values']` but `cluster_malpedia.values()` which will give you `ClusterValue` entries, which contain the meta and everything that you can access directly.

**Comment by sebdraven** [comment]
I've find this implementation :) https://github.com/yeti-platform/yeti/blob/mispgalaxies/extras/scripts/import_misp_galaxies.py#L24 

use ClusterValues item, transform each stage in dict to have information.

It's the "straight" implementation, you can close the issue :)

**Comment by adulau** [comment]
Thanks for the feedback. So maybe we are just lacking a documentation or a sample Jupyter notebook with such example ;-)

**Comment by sebdraven** [comment]
I'll do that today !
